use core::net::{Ipv4Addr, SocketAddr};
use futures::{future, prelude::*};
use pb_cheatsheet_com::{CheatsheetImage, FocusedWindowInfo, Info, TagsEither, World, RPC_PORT};
use std::collections::HashSet;
use tarpc::context::Context;
use tarpc::server::incoming::Incoming;
use tarpc::server::{self, Channel};
use tarpc::tokio_serde::formats::Json;

#[derive(Debug, Clone)]
struct TarpcServer {
    #[allow(unused)]
    peer_addr: SocketAddr,
}

impl pb_cheatsheet_com::World for TarpcServer {
    async fn focused_window(self, _: Context, info: FocusedWindowInfo) {
        println!("Received focused window");
        println!("{info:#?}");
    }

    async fn get_info(self, _: Context) -> Info {
        println!("Received get info request");
        Info {
            screen_width: 1920,
            screen_height: 1080,
            screen_orientation: pb_cheatsheet_com::ScreenOrientation::default(),
            cheatsheets: Vec::new(),
            wm_classes: Vec::new(),
        }
    }

    async fn upload_cheatsheet(
        self,
        _: Context,
        image: CheatsheetImage,
        name: String,
        tags: HashSet<String>,
    ) {
        println!("Received upload cheatsheet");
        println!("{image:#?}");
        println!("{name:#?}");
        println!("{tags:#?}");
    }

    async fn remove_cheatsheet(self, _: Context, name: String) {
        println!("Received remove cheatsheet");
        println!("{name:#?}");
    }

    async fn upload_screenshot(
        self,
        _: Context,
        screenshot: CheatsheetImage,
        name: Option<String>,
    ) {
        println!("Received upload screenshot");
        println!("{screenshot:#?}");
        println!("{name:#?}");
    }

    async fn clear_screenshot(self, _: Context) {
        println!("Received clear screenshot");
    }

    async fn add_cheatsheet_tags(self, _: Context, name: String, tags: HashSet<String>) {
        println!("Received add cheatsheet tags");
        println!("{name:#?}");
        println!("{tags:#?}");
    }

    async fn remove_cheatsheet_tags(self, _: Context, name: String, either: TagsEither) {
        println!("Received remove cheatsheet tags");
        println!("{name:#?}");
        println!("{either:#?}");
    }

    async fn add_wm_class_tags(self, _: Context, wm_class: String, tags: HashSet<String>) {
        println!("Received add wm class tags");
        println!("{wm_class:#?}");
        println!("{tags:#?}");
    }

    async fn remove_wm_class_tags(self, _: Context, wm_class: String, either: TagsEither) {
        println!("Received remove wm class tags");
        println!("{wm_class:#?}");
        println!("{either:#?}");
    }
}

async fn spawn_server() -> anyhow::Result<()> {
    let server_addr = (Ipv4Addr::new(0, 0, 0, 0), RPC_PORT);
    let mut listener = tarpc::serde_transport::tcp::listen(&server_addr, Json::default).await?;
    println!("Started RPC server with listening address: '{server_addr:?}'");
    listener.config_mut().max_frame_length(usize::MAX);
    listener
        // Ignore accept errors.
        .filter_map(|r| future::ready(r.ok()))
        .map(server::BaseChannel::with_defaults)
        // Limit channels to 1 per IP.
        .max_channels_per_key(1, |t| t.transport().peer_addr().unwrap().ip())
        // serve is generated by the service attribute. It takes as input any type implementing
        // the generated World trait.
        .map(|channel| {
            let server = TarpcServer {
                peer_addr: channel.transport().peer_addr().unwrap(),
            };
            channel.execute(server.serve()).for_each(|fut| async {
                tokio::spawn(fut);
            })
        })
        // Max 10 channels.
        .buffer_unordered(10)
        .for_each(|_| async {})
        .await;
    Ok(())
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let quit_token = tokio_util::sync::CancellationToken::new();

    // Ctrl-C cancel task
    let quit_token_c = quit_token.clone();
    tokio::spawn(async move {
        tokio::signal::ctrl_c()
            .await
            .expect("Awaited ctrl_c signal");
        quit_token_c.cancel();
    });

    tokio::select! {
        res = spawn_server() => {
            if let Err(err) = res {
                eprintln!("RPC Server failure: {err:?}");
            }
        }
        _ = quit_token.cancelled() => {}
    }

    println!("Exiting..");
    Ok(())
}
